name: NoLagg
main: com.bergerkiller.bukkit.nolagg.NoLagg
version: 1.48
author: bergerkiller
softdepend: [LogBlock, NoLaggChunks]
description: Plugin that prevents server lag caused by all sorts of events, from tnt to item drop spam
commands:
    nolagg:
        description: NoLagg is used to prevent lag on your server.
        usage: |
            /nolagg clear - Removes all items from your world and from the buffer (console uses all)
            /nolagg clear all - Removes all items from your server and from the buffer (players only)
permissions:
    nolagg.clear:
        description: Allows a player to clear all items at the server
        default: op
    nolagg.monitor:
        description: Allows a player to monitor server stats
        default: op
    nolagg.log:
        description: Allows a player to toggle server stats being written to a log file
        default: op
    nolagg.clearlog:
        description: Allows a player to clear the NoLagg log file
        default: op
    nolagg.fix:
        description: Allows a player to fix lighting issues in chunks around him
        default: op