name: NoLagg
main: com.bergerkiller.bukkit.nolagg.NoLagg
version: 1.0
author: bergerkiller
description: Plugin that prevents server lag caused by all sorts of events, from tnt to item drop spam
commands:
    nolagg:
        description: NoLagg is used to prevent lag on your server.
        usage: |
            /nolagg clear - Removes all items from your server and from the buffer
permissions:
    nolagg.clear:
        description: Allows a player to clear all items at the server
        default: op